### ISSUE TITLE
Canno't read property 'getAnnotations' of undefined

### ISSUE THREAD

**Issue by volter** [mtanda/grafana-histogram-panel#7]
While this message is perhaps harmless, as there is no meaningful place for annotations, it should be avoided.

**Comment by mtanda** [comment]
I don't see the message. I'll check it later again.

**Comment by popstas** [comment]
Same error in Chrome 50.0.2661.86 and Firefox 46 on Mac OS and Windows, using grafana 3.0.0-beta5 in docker.

**Comment by mtanda** [comment]
I can't replicate this issue yet.
At this line, the annotationsSrv should be assigned. The error might occur if it is not assigned.
https://github.com/mtanda/grafana-histogram-panel/blob/10f3cd0687cdaa8a435b035e50d1bf381a48575b/src/histogram_ctrl.js#L9

**Comment by popstas** [comment]
Can you show working panel json for any data from common system metrics?
I am using Telegraf and InfluxDB for collecting metrics.

**Comment by mtanda** [comment]
I don't use InfluxDB datasource, I use Prometheus datasource.
This is dashboard json, It works without error.
https://gist.github.com/mtanda/960910e125229e631e41bd872ab60075

My environment:
OS: Mac OS
Browser: Chrome 50.0.2661.86
Grafana: build local version of https://github.com/grafana/grafana/commit/70d03b7a1c40da4f34047d39e8f183f7f5dbf41b

**Comment by xadhoom** [comment]
I've a similar issue in my branch, I think is related to the minification process of grafana.
If you use a grafana package, the error will popup. if you use grafana from sources and/or not minified/uglyfied it will work.

still investigating on how to avoid it.

**Comment by mtanda** [comment]
Thanks. :-)
I'll investigate it too.

**Comment by mtanda** [comment]
I found this commit, https://github.com/xadhoom/grafana-panel-plugin-histogram/commit/f7053d08b65636290fcd0ea95b96b6c3cd6d0310 .
So I try to include the commit by this PR, https://github.com/mtanda/grafana-histogram-panel/pull/11 .

**Comment by xadhoom** [comment]
Hi,

yes we fixed it on friday, did not had time to send a PR to you.

basically, just remove the constructor from the HistogramCtrl and you're done.

(you don't need it, since the GraphCtrl already does that and knows about the private annotationsSrv)

**Comment by mtanda** [comment]
Thanks for fix!
I still get error in my environment, so I'll merge it after I fix the error.

**Comment by mtanda** [comment]
The annotationsSrv is private, I think it as the cause of error.

I fixed it by following PR.
https://github.com/mtanda/grafana-histogram-panel/pull/13
